name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 3 * * *'       # Täglich um 03:00 UTC
  workflow_dispatch:          # Manuell auslösbar

permissions:
  contents: write             # Erlaubt das Pushen ins Repo

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/streetwriters/notesnook-sync-server.git
          git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main --no-edit || true

      - name: Push changes
        run: git push origin main
